Google Oauth
JananiVijaykumar/BJC-Teacher-Tracker pull request #3
Opened 2019-11-10 08:02 UTC by yeyewangwang

Still, we don't have tests.

2019-11-11 22:44 UTC, zachchao requested changes

2019-11-11 22:44 UTC, zachchao commented on db/migrate/20191107223811_add_google_o_auth.rb
> +class AddGoogleOAuth < ActiveRecord::Migration
This migration is no longer needed

2019-11-11 22:44 UTC, zachchao commented on db/migrate/20191108235318_create_admins.rb
> +class CreateAdmins < ActiveRecord::Migration
As google o auth just gives us a name parameter do you think we should change this to just name and not first and last? or should it stay parallel with teachers?

2019-11-11 22:44 UTC, zachchao commented on db/migrate/20191110075355_add_admin_google_o_auth.rb
> +class AddAdminGoogleOAuth < ActiveRecord::Migration
Since this is one branch te add_admin_google_o_auth and create_admins migrations should be combined

2019-11-11 22:44 UTC, zachchao commented on app/controllers/admins_controller.rb
> +      flash[:color]= "valid"
need space between ] and =

2019-11-11 22:44 UTC, zachchao commented on app/controllers/admins_controller.rb
> +      flash[:color]= "invalid"
same style issue here

2019-11-12 00:04 UTC, yeyewangwang commented on db/migrate/20191107223811_add_google_o_auth.rb
> +class AddGoogleOAuth < ActiveRecord::Migration
Do you think we should leave it here in case we's like a teachers login?

2019-11-12 00:19 UTC, yeyewangwang commented on db/migrate/20191108235318_create_admins.rb
> +class CreateAdmins < ActiveRecord::Migration
I think there're auth.info.first_name and auth.info.last_name entries. I've changed the code to use these instead. (Also, it probably won't hurt making teachers and admins as similar as possible).

2019-11-12 00:20 UTC, yeyewangwang commented on db/migrate/20191110075355_add_admin_google_o_auth.rb
> +class AddAdminGoogleOAuth < ActiveRecord::Migration
I tried this but caused an error. For some reason, right now I'm using 1 migration again without any error.

2019-11-12 05:59 UTC, zachchao commented on db/migrate/20191107223811_add_google_o_auth.rb
> +class AddGoogleOAuth < ActiveRecord::Migration
Wasnt it a midterm or homework question where the answer was to delete code that was useless now? Less code is usually better.

2019-11-12 05:59 UTC, zachchao commented on db/migrate/20191108235318_create_admins.rb
> +class CreateAdmins < ActiveRecord::Migration
Okay great. Thank you

2019-11-12 06:00 UTC, zachchao commented on db/migrate/20191110075355_add_admin_google_o_auth.rb
> +class AddAdminGoogleOAuth < ActiveRecord::Migration
Yeah youll have to make your migrations go down one then redo them, that is only a local problem

2019-11-12 06:01 UTC, zachchao commented on db/migrate/20191110075355_add_admin_google_o_auth.rb
> +class AddAdminGoogleOAuth < ActiveRecord::Migration
```rake db:rollback```

2019-11-12 06:04 UTC, zachchao commented on db/migrate/20191107223811_add_google_o_auth.rb
> +class AddGoogleOAuth < ActiveRecord::Migration
If you choose to keep though it isnt a big deal

2019-11-12 06:43 UTC, yeyewangwang commented on db/migrate/20191107223811_add_google_o_auth.rb
> +class AddGoogleOAuth < ActiveRecord::Migration
Good to know! Thank you!

2019-11-12 15:44 UTC, zachchao approved these changes

2019-11-12 20:19 UTC, merged